version: "3.8"

services: 
    db:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile.dev
        volumes: 
            - ./docker-volumes-data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        depends_on:
            - db
        volumes: 
            - /usr/app/node_modules
            - ./:/usr/app
        ports: 
            - 3000:3000